name: BuildingGenerator
main: fr.cr3art.spigot.Main
version: 0.0.1
api-version: 1.14
commands:
   exmple:
     description: description
     aliases: [aliasA,aliasB]
   example:
     description: commande d'example
   inventaire_main:
     description: description
     aliases: [aliasA,aliasB]
   inventaire_arg:
     description: description
     aliases: [aliasA,aliasB]
   operation:
     description: description
     aliases: [aliasA,aliasB]
   generate:
     description: description
   menu:
     description: description
     aliases: [aliasA,aliasB]
permissions:
  exmplePermision:
   description: Allows foo command
   default: op
